# Set configuration parameters
DWT_LEVEL = 2
MARK_SIZE = 32
BETA = 0.2
N_IMAGES_LIMIT = 10
MAX_N_ATTACKS = 3
N_AVAILABLE_ATTACKS = 7
RUNS_PER_IMAGE = 30
N_FALSE_WATERMARKS_GENERATIONS = 1
TARGET_FPR = 0.03
PARAMETERS_FOLDER_PATH = 'parameters/'
IMG_FOLDER_PATH = 'images/'
DEFAULT_SUBBAND = ["LL"]
MAX_WORKERS = 6
