# Set configuration parameters
N_IMAGES_LIMIT = 10
N_AVAILABLE_ATTACKS = 7
MAX_N_ATTACKS = 5
MIN_N_ATTACKS = 2
RUNS_PER_IMAGE = 10
N_FALSE_WATERMARKS_GENERATIONS = 1
TARGET_FPR = 0.08
PARAMETERS_FOLDER_PATH = 'parameters/'
IMG_FOLDER_PATH = 'images/to-watermark/'
MAX_WORKERS = 100

DWT_LEVEL = 4
MARK_SIZE = 32
ALPHA = 55
SUBBANDS = ["LL"]