# Set configuration parameters
DWT_LEVEL = 1
MARK_SIZE = 32
DEFAULT_ALPHA = 250
N_IMAGES_LIMIT = 5 #1000
MAX_N_ATTACKS = 3
N_AVAILABLE_ATTACKS = 6
RUNS_PER_IMAGE = 3 #30
N_FALSE_WATERMARKS_GENERATIONS = 1
TARGET_FPR = 0.03
PARAMETERS_FOLDER_PATH = 'parameters/'
IMG_FOLDER_PATH = 'images/'
